### ISSUE TITLE
Med comment on Dynamic Properties

### ISSUE THREAD

**Issue by theri** [theri/draft-enghardt-panrg-path-properties#17]
Last one...

On "Latency", "Latency variation", "Packet loss":
[Med44]: Please use conventional terms : one-way delay, one-way delay variation, one-way loss, etc.
Yes, it might be useful to use terms as defined, e.g., in IPPM, and add references here.

**Comment by cyrill-k** [comment]
I guess there are two ways for doing this:
- Use the same terms as IPPM and always add a disclaimer that the terms are not exactly equivalent (e.g., different path definition, not only IP traffic)
- Keep existing names and add reference to IPPM drafts

I like the first option more as it keeps the terminology as consistent as possible, we just need to make sure to clearly state the difference to IPPM.

I also made slight adjustments to the descriptions:
- link capacity (no longer defined on subpath and path; we can use aggregated properties for that)
- one-way delay variation: added difference between IPPM and us (variation on packets on the same flow instead of packets with same src/dst IP address)
- packet loss: added reference for loss pattern and loss periode

Commit: 15a84c4abca9ebfa44eb625763d66cd450bdcc1c

What do you think?

**Comment by theri** [comment]
Thanks for this!
I like the first option as well, as these terms seem more clear to me than the ones we had.

So, please merge that branch and then close this issue. Thanks! :)

By the way, I'll try to make progress on the terminology and the other stuff this week.
